import { mkdir, readdir, writeFile } from "node:fs/promises";

const configsDirectory = "./configs/webpack";

const bundleConfigs = await readdir(configsDirectory).then((files) =>
  files.filter((file) => file.startsWith("bundle"))
);

await mkdir("./dist", { recursive: true });
await writeFile(
  "./dist/manifest.bundles.js",
  `// DO NOT EDIT: THIS FILE IS AUTOMATICALLY GENERATED //

/** @typedef {typeof bundles[number]} Bundle */

/** generated from webpack.config.js */
export const bundles = /** @type {const} @satisfies {readonly string[]} */ ([
\t${bundleConfigs.map((name) => `"${name}"`).join(",\n\t")},
]);
`,
  "utf-8"
);

export default await Promise.all(
  bundleConfigs.map((name) =>
    import(`${configsDirectory}/${name}`).then((config) => config.default)
  )
);
